import { EdgeColors, edgeStyle } from '../styles'

export const bondingEdgesMobile = [
  {
    id: 'Concave Treasury-CNV',
    source: 'Concave Treasury',
    target: 'CNV',
    sourceHandle: 'topSource',
    targetHandle: 'bottomTarget',
    style: { ...edgeStyle, stroke: EdgeColors.CornflowerBlue },
    animated: true,
  },
  {
    id: 'Concave Treasury-Proxy Admin',
    source: 'Concave Treasury',
    target: 'Proxy Admin',
    sourceHandle: 'leftSource',
    targetHandle: 'bottomTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Orange },
    animated: true,
  },
  {
    id: 'Concave Treasury-Policy Multisig',
    source: 'Concave Treasury',
    target: 'Policy Multisig',
    sourceHandle: 'bottomSource',
    targetHandle: 'topTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Orange },
    animated: true,
  },
  {
    id: 'Concave Treasury-AccrualBondsV1 (Proxy)',
    source: 'Concave Treasury',
    target: 'AccrualBondsV1 (Proxy)',
    sourceHandle: 'leftSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Orange },
    animated: true,
  },
  {
    id: 'Policy Multisig-AccrualBondsV1 (Proxy)',
    source: 'Policy Multisig',
    target: 'AccrualBondsV1 (Proxy)',
    sourceHandle: 'topSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Orange },
    animated: true,
  },
  {
    id: 'Proxy Admin-AccrualBondsV1 (Proxy)',
    source: 'Proxy Admin',
    target: 'AccrualBondsV1 (Proxy)',
    sourceHandle: 'bottomSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Teal },
    animated: true,
  },
  {
    id: 'AccrualBondsV1 (Proxy)-Proxy Admin',
    source: 'AccrualBondsV1 (Proxy)',
    target: 'Proxy Admin',
    sourceHandle: 'rightSource',
    targetHandle: 'bottomTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Teal },
    animated: true,
  },
  {
    id: 'AccrualBondsV1 (Proxy)-user',
    source: 'AccrualBondsV1 (Proxy)',
    target: 'user',
    sourceHandle: 'topSource',
    targetHandle: 'bottomTarget',
    style: { ...edgeStyle, stroke: EdgeColors.CornflowerBlue },
    animated: true,
  },
  {
    id: 'user-AccrualBondsV1 (Proxy)',
    source: 'user',
    target: 'AccrualBondsV1 (Proxy)',
    sourceHandle: 'bottomSource',
    targetHandle: 'topTarget',
    style: { ...edgeStyle, stroke: EdgeColors.CornflowerBlue },
    animated: true,
  },
  {
    id: 'AccrualBondsV1 (Proxy)-AccrualBondsV1 (Impl)',
    source: 'AccrualBondsV1 (Proxy)',
    target: 'AccrualBondsV1 (Impl)',
    sourceHandle: 'rightSource',
    targetHandle: 'topTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Purple },
    animated: true,
  },
  {
    id: 'AccrualBondsV1 (Impl)-AccrualBondsV1 (Proxy)',
    source: 'AccrualBondsV1 (Impl)',
    target: 'AccrualBondsV1 (Proxy)',
    sourceHandle: 'topSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Purple },
    animated: true,
  },
  {
    id: 'AccrualBondsV1 (Proxy)-ValueShuttle',
    source: 'AccrualBondsV1 (Proxy)',
    target: 'ValueShuttle',
    sourceHandle: 'bottomSource',
    targetHandle: 'topTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Purple },
    animated: true,
  },
  {
    id: 'ValueShuttle-CO-OP Treasury',
    source: 'ValueShuttle',
    target: 'CO-OP Treasury',
    sourceHandle: 'bottomSource',
    targetHandle: 'topTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Green },
    animated: true,
  },
]
