import { EdgeColors, edgeStyle } from '../styles'

export const stakingEdgesMobile = [
  {
    id: 'Concave Treasury-CNV',
    source: 'Concave Treasury',
    target: 'CNV',
    sourceHandle: 'bottomSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Orange },
    animated: true,
  },
  {
    id: 'Concave Treasury-Proxy Admin',
    source: 'Concave Treasury',
    target: 'Proxy Admin',
    sourceHandle: 'topSource',
    targetHandle: 'bottomTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Orange },
    animated: true,
  },
  {
    id: 'Concave Treasury-StakingV1 (Proxy)',
    source: 'Concave Treasury',
    target: 'StakingV1 (Proxy)',
    sourceHandle: 'topSource',
    targetHandle: 'bottomTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Orange },
    animated: true,
  },
  {
    id: 'Policy Multisig-StakingV1 (Proxy)',
    source: 'Policy Multisig',
    target: 'StakingV1 (Proxy)',
    sourceHandle: 'topSource',
    targetHandle: 'bottomTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Orange },
    animated: true,
  },
  {
    id: 'Proxy Admin-StakingV1 (Proxy)',
    source: 'Proxy Admin',
    target: 'StakingV1 (Proxy)',
    sourceHandle: 'leftSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Teal },
    animated: true,
  },
  {
    id: 'StakingV1 (Proxy)-Proxy Admin',
    source: 'StakingV1 (Proxy)',
    target: 'Proxy Admin',
    sourceHandle: 'rightSource',
    targetHandle: 'leftTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Teal },
    animated: true,
  },
  {
    id: 'StakingV1 (Proxy)-lsdCNV',
    source: 'StakingV1 (Proxy)',
    target: 'lsdCNV',
    sourceHandle: 'topSource',
    targetHandle: 'bottomTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Teal },
    animated: true,
  },
  {
    id: 'StakingV1 (Proxy)-CO-OP Treasury',
    source: 'StakingV1 (Proxy)',
    target: 'CO-OP Treasury',
    sourceHandle: 'bottomSource',
    targetHandle: 'topTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Teal },
    animated: true,
  },
  {
    id: 'StakingV1 (Proxy)-StakingV1 (Impl)',
    source: 'StakingV1 (Proxy)',
    target: 'StakingV1 (Impl)',
    sourceHandle: 'leftSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Teal },
    animated: true,
  },
  {
    id: 'StakingV1 (Impl)-StakingV1 (Proxy)',
    source: 'StakingV1 (Impl)',
    target: 'StakingV1 (Proxy)',
    sourceHandle: 'rightSource',
    targetHandle: 'leftTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Teal },
    animated: true,
  },
  {
    id: 'ValueShuttle-StakingV1 (Proxy)',
    source: 'ValueShuttle',
    target: 'StakingV1 (Proxy)',
    sourceHandle: 'bottomSource',
    targetHandle: 'topTarget',
    style: { ...edgeStyle, stroke: EdgeColors.Green },
    animated: true,
  },
  {
    id: 'lsdCNV-user',
    source: 'lsdCNV',
    target: 'user',
    sourceHandle: 'leftSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.CornflowerBlue },
    animated: true,
  },
  {
    id: 'user-ValueShuttle',
    source: 'user',
    target: 'ValueShuttle',
    sourceHandle: 'leftSource',
    targetHandle: 'rightTarget',
    style: { ...edgeStyle, stroke: EdgeColors.CornflowerBlue },
    animated: true,
  },
]
