export const ContractABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'uint64', name: 'auctionEndPeriod', type: 'uint64' },
    ],
    name: 'AuctionPeriodUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'auctionSettler', type: 'address' },
    ],
    name: 'AuctionSettled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'nftOwner', type: 'address' },
    ],
    name: 'AuctionWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'masterTokenId', type: 'uint256' },
      { indexed: false, internalType: 'uint256[]', name: 'batchTokens', type: 'uint256[]' },
      { indexed: false, internalType: 'address', name: 'nftSeller', type: 'address' },
      { indexed: false, internalType: 'address', name: 'erc20Token', type: 'address' },
      { indexed: false, internalType: 'uint128', name: 'buyNowPrice', type: 'uint128' },
      { indexed: false, internalType: 'address', name: 'whitelistedBuyer', type: 'address' },
      { indexed: false, internalType: 'address[]', name: 'feeRecipients', type: 'address[]' },
      { indexed: false, internalType: 'uint32[]', name: 'feePercentages', type: 'uint32[]' },
    ],
    name: 'BatchSaleCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'bidder', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'ethAmount', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'erc20Token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenAmount', type: 'uint256' },
    ],
    name: 'BidMade',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'highestBidder', type: 'address' },
    ],
    name: 'BidWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'HighestBidTaken',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'nftSeller', type: 'address' },
      { indexed: false, internalType: 'uint128', name: 'nftHighestBid', type: 'uint128' },
      { indexed: false, internalType: 'address', name: 'nftHighestBidder', type: 'address' },
      { indexed: false, internalType: 'address', name: 'nftRecipient', type: 'address' },
    ],
    name: 'NFTTransferredAndSellerPaid',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'nftOwner', type: 'address' },
    ],
    name: 'NFTWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'nftSeller', type: 'address' },
      { indexed: false, internalType: 'address', name: 'erc20Token', type: 'address' },
      { indexed: false, internalType: 'uint128', name: 'minPrice', type: 'uint128' },
      { indexed: false, internalType: 'uint128', name: 'buyNowPrice', type: 'uint128' },
      { indexed: false, internalType: 'uint32', name: 'auctionBidPeriod', type: 'uint32' },
      { indexed: false, internalType: 'uint32', name: 'bidIncreasePercentage', type: 'uint32' },
      { indexed: false, internalType: 'address[]', name: 'feeRecipients', type: 'address[]' },
      { indexed: false, internalType: 'uint32[]', name: 'feePercentages', type: 'uint32[]' },
    ],
    name: 'NftAuctionCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'masterTokenId', type: 'uint256' },
      { indexed: false, internalType: 'uint256[]', name: 'batchTokens', type: 'uint256[]' },
      { indexed: false, internalType: 'address', name: 'nftSeller', type: 'address' },
      { indexed: false, internalType: 'address', name: 'erc20Token', type: 'address' },
      { indexed: false, internalType: 'uint128', name: 'minPrice', type: 'uint128' },
      { indexed: false, internalType: 'uint128', name: 'buyNowPrice', type: 'uint128' },
      { indexed: false, internalType: 'uint32', name: 'auctionBidPeriod', type: 'uint32' },
      { indexed: false, internalType: 'uint32', name: 'bidIncreasePercentage', type: 'uint32' },
      { indexed: false, internalType: 'address[]', name: 'feeRecipients', type: 'address[]' },
      { indexed: false, internalType: 'uint32[]', name: 'feePercentages', type: 'uint32[]' },
    ],
    name: 'NftBatchAuctionCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Paused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'bytes32', name: 'previousAdminRole', type: 'bytes32' },
      { indexed: true, internalType: 'bytes32', name: 'newAdminRole', type: 'bytes32' },
    ],
    name: 'RoleAdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
    ],
    name: 'RoleGranted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
    ],
    name: 'RoleRevoked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'nftContractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'nftSeller', type: 'address' },
      { indexed: false, internalType: 'address', name: 'erc20Token', type: 'address' },
      { indexed: false, internalType: 'uint128', name: 'buyNowPrice', type: 'uint128' },
      { indexed: false, internalType: 'address', name: 'whitelistedBuyer', type: 'address' },
      { indexed: false, internalType: 'address[]', name: 'feeRecipients', type: 'address[]' },
      { indexed: false, internalType: 'uint32[]', name: 'feePercentages', type: 'uint32[]' },
    ],
    name: 'SaleCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Unpaused',
    type: 'event',
  },
  {
    inputs: [],
    name: 'ADMIN_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: '_batchTokenIds', type: 'uint256[]' },
      { internalType: 'address', name: '_erc20Token', type: 'address' },
      { internalType: 'uint128', name: '_minPrice', type: 'uint128' },
      { internalType: 'uint128', name: '_buyNowPrice', type: 'uint128' },
      { internalType: 'uint32', name: '_auctionBidPeriod', type: 'uint32' },
      { internalType: 'uint32', name: '_bidIncreasePercentage', type: 'uint32' },
      { internalType: 'address[]', name: '_feeRecipients', type: 'address[]' },
      { internalType: 'uint32[]', name: '_feePercentages', type: 'uint32[]' },
    ],
    name: 'createBatchNftAuction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: '_batchTokenIds', type: 'uint256[]' },
      { internalType: 'address', name: '_erc20Token', type: 'address' },
      { internalType: 'uint128', name: '_buyNowPrice', type: 'uint128' },
      { internalType: 'address', name: '_whitelistedBuyer', type: 'address' },
      { internalType: 'address[]', name: '_feeRecipients', type: 'address[]' },
      { internalType: 'uint32[]', name: '_feePercentages', type: 'uint32[]' },
    ],
    name: 'createBatchSale',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: '_batchTokenIds', type: 'uint256[]' },
      { internalType: 'address', name: '_erc20Token', type: 'address' },
      { internalType: 'uint128', name: '_minPrice', type: 'uint128' },
      { internalType: 'uint128', name: '_buyNowPrice', type: 'uint128' },
      { internalType: 'address[]', name: '_feeRecipients', type: 'address[]' },
      { internalType: 'uint32[]', name: '_feePercentages', type: 'uint32[]' },
    ],
    name: 'createDefaultBatchNftAuction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_erc20Token', type: 'address' },
      { internalType: 'uint128', name: '_minPrice', type: 'uint128' },
      { internalType: 'uint128', name: '_buyNowPrice', type: 'uint128' },
      { internalType: 'address[]', name: '_feeRecipients', type: 'address[]' },
      { internalType: 'uint32[]', name: '_feePercentages', type: 'uint32[]' },
    ],
    name: 'createDefaultNftAuction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'createMarketItem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_erc20Token', type: 'address' },
      { internalType: 'uint128', name: '_minPrice', type: 'uint128' },
      { internalType: 'uint128', name: '_buyNowPrice', type: 'uint128' },
      { internalType: 'uint32', name: '_auctionBidPeriod', type: 'uint32' },
      { internalType: 'uint32', name: '_bidIncreasePercentage', type: 'uint32' },
      { internalType: 'address[]', name: '_feeRecipients', type: 'address[]' },
      { internalType: 'uint32[]', name: '_feePercentages', type: 'uint32[]' },
    ],
    name: 'createNewNftAuction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_erc20Token', type: 'address' },
      { internalType: 'uint128', name: '_buyNowPrice', type: 'uint128' },
      { internalType: 'address', name: '_whitelistedBuyer', type: 'address' },
      { internalType: 'address[]', name: '_feeRecipients', type: 'address[]' },
      { internalType: 'uint32[]', name: '_feePercentages', type: 'uint32[]' },
    ],
    name: 'createSale',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'defaultAuctionBidPeriod',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'defaultBidIncreasePercentage',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fetchItemsForSale',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'itemId', type: 'uint256' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'address', name: 'nftAddress', type: 'address' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'bool', name: 'forSale', type: 'bool' },
        ],
        internalType: 'struct ConcaveNFTMarketplace.MarketItem[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fetchMyOwnedNFTs',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'itemId', type: 'uint256' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'address', name: 'nftAddress', type: 'address' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'bool', name: 'forSale', type: 'bool' },
        ],
        internalType: 'struct ConcaveNFTMarketplace.MarketItem[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
    name: 'getRoleAdmin',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'hasRole',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'initialize', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_erc20Token', type: 'address' },
      { internalType: 'uint128', name: '_tokenAmount', type: 'uint128' },
    ],
    name: 'makeBid',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_erc20Token', type: 'address' },
      { internalType: 'uint128', name: '_tokenAmount', type: 'uint128' },
      { internalType: 'address', name: '_nftRecipient', type: 'address' },
    ],
    name: 'makeCustomBid',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maximumMinPricePercentage',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'minimumSettableIncreasePercentage',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'nftContractAuctions',
    outputs: [
      { internalType: 'uint32', name: 'bidIncreasePercentage', type: 'uint32' },
      { internalType: 'uint32', name: 'auctionBidPeriod', type: 'uint32' },
      { internalType: 'uint64', name: 'auctionEnd', type: 'uint64' },
      { internalType: 'uint128', name: 'minPrice', type: 'uint128' },
      { internalType: 'uint128', name: 'buyNowPrice', type: 'uint128' },
      { internalType: 'uint128', name: 'nftHighestBid', type: 'uint128' },
      { internalType: 'address', name: 'nftHighestBidder', type: 'address' },
      { internalType: 'address', name: 'nftSeller', type: 'address' },
      { internalType: 'address', name: 'whitelistedBuyer', type: 'address' },
      { internalType: 'address', name: 'nftRecipient', type: 'address' },
      { internalType: 'address', name: 'ERC20Token', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'nftOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'ownerOfNFT',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'renounceRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'nftContractAddress', type: 'address' }],
    name: 'setNFTContractAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'settleAuction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'takeHighestBid',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'toggleForSale',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'tokenIdToItemIds',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'unlockPositionHandler',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'unpause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'uint128', name: '_newBuyNowPrice', type: 'uint128' },
    ],
    name: 'updateBuyNowPrice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'uint128', name: '_newMinPrice', type: 'uint128' },
    ],
    name: 'updateMinimumPrice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_newWhitelistedBuyer', type: 'address' },
    ],
    name: 'updateWhitelistedBuyer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdrawAllFailedCredits',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'withdrawAuction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'withdrawBid',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_tokenId', type: 'uint256' }],
    name: 'withdrawNft',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
