query GET_LAST_BASE_VAPR {
  logStakingV1_PoolRewarded(where: { balance: { _gt: "0" } }) {
    base_vAPR
  }
}

query GET_LAST_POOLS_TOTAL_VAPR {
  totalVapr {
    pool0TotalBaseVapr
    pool1TotalBaseVapr
    pool2TotalBaseVapr
    pool3TotalBaseVapr
  }
}
query GET_LAST_POOLID_VAPR($poolID: numeric) {
  logStakingV1_PoolRewarded(
    where: { poolID: { _eq: $poolID } }
    order_by: { txBlockNumber: desc }
    limit: 1
  ) {
    base_vAPR
  }
}

query GET_LAST_POOLS_TOTAL_VAPR {
  totalVapr {
    pool0TotalBaseVapr
    pool1TotalBaseVapr
    pool2TotalBaseVapr
    pool3TotalBaseVapr
  }
}