query GET_AMM_CNV_PRICE {
  cnvData {
    data {
      last
      ticker
    }
  }
}

query GET_AMM_CNV_INFOS {
  cnvData {
    data {
      last
      marketCap
      totalSupply
      circulatingSupply
    }
  }
}