query GET_STACKINGV1_LAST100_EVENTS {
  logStakingV1(order_by: { blockNumber: desc }, limit: 100) {
    blockNumber
    txHash
    poolID
    tokenID
    sold
    from
    to
    amountLocked
    lockedUntil
  }
}

query GET_STACKINGV1_BY_POOL_ID($poolID: numeric_comparison_exp) {
  logStakingV1(order_by: { blockNumber: desc }, where: { poolID: $poolID }, limit: 10) {
    blockNumber
    txHash
    poolID
    tokenID
    sold
    from
    to
    amountLocked
    lockedUntil
  }
}

query GET_STAKINGV1_LAST100_LOCK {
  logStakingV1_Lock {
    txHash
    txBlockNumber
    poolID
    positionID
    to
    amount
  }
}

query GET_ACCRUALBONDV1_LAST10_SOLD {
  logAccrualBondsV1_BondSold(order_by: { txBlockNumber: desc }, limit: 10) {
    timestamp
    inputToken
    inputaAmount
    method
    output
  }
}
