mutation InsertUser($address: String!) {
  insert_user_one(object: { address: $address }) {
    id
    address
  }
}

query UserByAddress($address: String!) {
  user(where: { address: { _eq: $address } }) {
    id
    address
    chainId
  }
}
