export const BOND_ABI = [
  { inputs: [], name: 'BAD_OUTPUT', type: 'error' },
  { inputs: [], name: 'INSUFFICIENT_LIQUIDITY', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'caller', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newBeneficiary', type: 'address' },
    ],
    name: 'BeneficiarySet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'bonder', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'bondId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'output', type: 'uint256' },
    ],
    name: 'BondRedeemed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'bonder', type: 'address' },
      { indexed: true, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'input', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'output', type: 'uint256' },
    ],
    name: 'BondSold',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'caller', type: 'address' },
      { indexed: true, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'virtualReserves', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'halfLife', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'levelBips', type: 'uint256' },
    ],
    name: 'QuoteAssetAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'caller', type: 'address' },
      { indexed: true, internalType: 'address', name: 'token', type: 'address' },
    ],
    name: 'QuoteAssetRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'caller', type: 'address' },
      { indexed: true, internalType: 'address', name: 'token', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'virtualReserves', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'halfLife', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'levelBips', type: 'uint256' },
    ],
    name: 'QuotePricingSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'caller', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'newControlWeight', type: 'uint256' },
    ],
    name: 'VirtualOutputReservesSet',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'virtualReserves', type: 'uint256' },
      { internalType: 'uint256', name: 'halfLife', type: 'uint256' },
      { internalType: 'uint256', name: 'levelBips', type: 'uint256' },
    ],
    name: 'addQuoteAsset',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'beneficiary',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'input', type: 'uint256' },
    ],
    name: 'getAmountOut',
    outputs: [{ internalType: 'uint256', name: 'output', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAvailableSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'getSpotPrice',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_term', type: 'uint256' },
      { internalType: 'uint256', name: '_vyReserves', type: 'uint256' },
      { internalType: 'address', name: '_outputToken', type: 'address' },
      { internalType: 'address', name: '_beneficiary', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'virtualReserves', type: 'uint256' },
      { internalType: 'uint256', name: 'halfLife', type: 'uint256' },
      { internalType: 'uint256', name: 'levelBips', type: 'uint256' },
    ],
    name: 'modifyQuotePricing',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: 'tokens', type: 'address[]' },
      { internalType: 'uint256[]', name: 'virtualReserves', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'halfLives', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'levelBips', type: 'uint256[]' },
    ],
    name: 'modifyQuotePricingBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'cw', type: 'uint256' }],
    name: 'modifyVirtualOutputReserves',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'outputToken',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'positions',
    outputs: [
      { internalType: 'uint256', name: 'owed', type: 'uint256' },
      { internalType: 'uint256', name: 'redeemed', type: 'uint256' },
      { internalType: 'uint256', name: 'creation', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'input', type: 'uint256' },
      { internalType: 'uint256', name: 'minOutput', type: 'uint256' },
    ],
    name: 'purchaseBond',
    outputs: [{ internalType: 'uint256', name: 'output', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'input', type: 'uint256' },
      { internalType: 'uint256', name: 'minOutput', type: 'uint256' },
      { internalType: 'uint256', name: 'deadline', type: 'uint256' },
      { internalType: 'uint8', name: 'v', type: 'uint8' },
      { internalType: 'bytes32', name: 'r', type: 'bytes32' },
      { internalType: 'bytes32', name: 's', type: 'bytes32' },
    ],
    name: 'purchaseBondUsingPermit',
    outputs: [{ internalType: 'uint256', name: 'output', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint256', name: 'input', type: 'uint256' },
      { internalType: 'uint256', name: 'minOutput', type: 'uint256' },
      { internalType: 'uint256', name: 'expiry', type: 'uint256' },
      { internalType: 'uint256', name: 'nonce', type: 'uint256' },
      { internalType: 'uint8', name: 'v', type: 'uint8' },
      { internalType: 'bytes32', name: 'r', type: 'bytes32' },
      { internalType: 'bytes32', name: 's', type: 'bytes32' },
    ],
    name: 'purchaseBondUsingPermitAllowed',
    outputs: [{ internalType: 'uint256', name: 'output', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'quoteInfo',
    outputs: [
      { internalType: 'uint256', name: 'virtualReserves', type: 'uint256' },
      { internalType: 'uint256', name: 'lastUpdate', type: 'uint256' },
      { internalType: 'uint256', name: 'halfLife', type: 'uint256' },
      { internalType: 'uint256', name: 'levelBips', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'uint256', name: 'bid', type: 'uint256' },
    ],
    name: 'redeemBond',
    outputs: [{ internalType: 'uint256', name: 'output', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'removeQuoteAsset',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newBeneficiary', type: 'address' }],
    name: 'setBeneficiary',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'term',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalAssets',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalDebt',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'vyReserves',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
]
