export const DN_STRATEGY_ABI = [
  'constructor(address _vault, address _homoraBank, address _sushiSwapSpell, address _uniswapV2Router, address _token1, address _concaveOracle, address _lpTokenPair, uint256 _pid, address _ethTokenAddress)',
  'event EmergencyExitEnabled()',
  'event Harvested(uint256 profit, uint256 loss, uint256 debtPayment, uint256 debtOutstanding)',
  'event Received(address, uint256)',
  'event SetDoHealthCheck(bool)',
  'event SetHealthCheck(address)',
  'event Tended()',
  'event UpdatedDebtThreshold(uint256 debtThreshold)',
  'event UpdatedKeeper(address newKeeper)',
  'event UpdatedMaxReportDelay(uint256 delay)',
  'event UpdatedMetadataURI(string metadataURI)',
  'event UpdatedMinReportDelay(uint256 delay)',
  'event UpdatedProfitFactor(uint256 profitFactor)',
  'event UpdatedRewards(address rewards)',
  'event UpdatedStrategist(address newStrategist)',
  'event debugAddress(address emitAddr)',
  'event debugBool(bool emitBool)',
  'event debugString(string str)',
  'event debugUint(uint256 emitUint)',
  'function apiVersion() pure returns (string)',
  'function borrowBalanceStored(uint256 positionId, address token) view returns (uint256)',
  'function concaveOracle() view returns (address)',
  'function debtThreshold() view returns (uint256)',
  'function delegatedAssets() view returns (uint256)',
  'function doHealthCheck() view returns (bool)',
  'function emergencyExit() view returns (bool)',
  'function estimatedTotalAssets() view returns (uint256)',
  'function ethToWant(uint256 _amtInWei) view returns (uint256)',
  'function ethTokenAddress() view returns (address)',
  'function getBankInfo(address token) view returns (bool isListed, address cToken, uint256 reserve, uint256 totalDebt, uint256 totalShare)',
  'function getBorrowETHValue(uint256 positionId) view returns (uint256)',
  'function getCollateralETHValue(uint256 positionId) view returns (uint256)',
  'function getETHPx(address token) view returns (uint256)',
  'function getPendingRewardForSushiswap(uint256 _positionId) view returns (uint256)',
  'function getPositionDebtShareOf(uint256 positionId, address token) view returns (uint256)',
  'function getPositionDebts(uint256 positionId) view returns (address[] tokens, uint256[] debts)',
  'function getPositionId() view returns (uint256)',
  'function getPositionInfo(uint256 positionId) view returns (address owner, address collToken, uint256 collId, uint256 collateralSize)',
  'function getSushi() view returns (address)',
  'function harvest()',
  'function harvestSushiswap(uint256 positionID)',
  'function harvestTrigger(uint256 callCostInWei) view returns (bool)',
  'function healthCheck() view returns (address)',
  'function homoraBank() view returns (address)',
  'function isActive() view returns (bool)',
  'function keeper() view returns (address)',
  'function maxReportDelay() view returns (uint256)',
  'function metadataURI() view returns (string)',
  'function migrate(address _newStrategy)',
  'function minReportDelay() view returns (uint256)',
  'function name() pure returns (string)',
  'function openOrIncreasePositionSushiswap(tuple(uint256 positionID, address token0, address token1, uint256 supplyToken0, uint256 supplyToken1, uint256 supplyLp, uint256 borrowToken0, uint256 borrowToken1, uint256 pid) inputData) returns (uint256)',
  'function openPosition()',
  'function profitFactor() view returns (uint256)',
  'function reducePositionSushiswap(tuple(uint256 positionID, address token0, address token1, uint256 amtLPTake, uint256 amtLPWithdraw, uint256 repayAmtToken0, uint256 repayAmtToken1, uint256 amountLPRepay) inputData)',
  'function relevantHomoraSpell() view returns (address)',
  'function rewards() view returns (address)',
  'function setDebtThreshold(uint256 _debtThreshold)',
  'function setDoHealthCheck(bool _doHealthCheck)',
  'function setEmergencyExit()',
  'function setHealthCheck(address _healthCheck)',
  'function setKeeper(address _keeper)',
  'function setMaxReportDelay(uint256 _delay)',
  'function setMetadataURI(string _metadataURI)',
  'function setMinReportDelay(uint256 _delay)',
  'function setPositionId(uint256 _positionId)',
  'function setProfitFactor(uint256 _profitFactor)',
  'function setRewards(address _rewards)',
  'function setStrategist(address _strategist)',
  'function strategist() view returns (address)',
  'function support(address token) view returns (bool)',
  'function swap(address _tokenIn, uint256 _amountIn, address _tokenOut, address[] _path, address _to) returns (uint256 amountOut)',
  'function swap(address _tokenIn, uint256 _amountIn, address _tokenOut, address _to) returns (uint256 amountOut)',
  'function sweep(address _token)',
  'function tend(bool _overrideMode)',
  'function tendTrigger() view returns (bool)',
  'function uniswapV2Router() view returns (address)',
  'function vault() view returns (address)',
  'function want() view returns (address)',
  'function withdraw(uint256 _amountNeeded) returns (uint256 _loss)',
]
