export const DN_VAULT_ABI = [
  'event TestLogInt(uint256 amount)',
  'event TestLogAddr(address indexed addr)',
  'event TestLogBool(bool flag)',
  'event Transfer(address indexed sender, address indexed receiver, uint256 value)',
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
  'event Deposit(address indexed recipient, uint256 shares, uint256 amount)',
  'event Withdraw(address indexed recipient, uint256 shares, uint256 amount)',
  'event Sweep(address indexed token, uint256 amount)',
  'event LockedProfitDegradationUpdated(uint256 value)',
  'event StrategyAdded(address indexed strategy, uint256 debtRatio, uint256 minDebtPerHarvest, uint256 maxDebtPerHarvest, uint256 performanceFee)',
  'event StrategyReported(address indexed strategy, uint256 gain, uint256 loss, uint256 debtPaid, uint256 totalGain, uint256 totalLoss, uint256 totalDebt, uint256 debtAdded, uint256 debtRatio)',
  'event UpdateGovernance(address governance)',
  'event NewPendingGovernance(address governance)',
  'event UpdateManagement(address management)',
  'event UpdateRewards(address rewards)',
  'event UpdateDepositLimit(uint256 depositLimit)',
  'event UpdatePerformanceFee(uint256 performanceFee)',
  'event UpdateManagementFee(uint256 managementFee)',
  'event UpdateGuardian(address guardian)',
  'event EmergencyShutdown(bool active)',
  'event UpdateWithdrawalQueue(address[10] queue)',
  'event StrategyUpdateDebtRatio(address indexed strategy, uint256 debtRatio)',
  'event StrategyUpdateMinDebtPerHarvest(address indexed strategy, uint256 minDebtPerHarvest)',
  'event StrategyUpdateMaxDebtPerHarvest(address indexed strategy, uint256 maxDebtPerHarvest)',
  'event StrategyUpdatePerformanceFee(address indexed strategy, uint256 performanceFee)',
  'event StrategyMigrated(address indexed oldVersion, address indexed newVersion)',
  'event StrategyRevoked(address indexed strategy)',
  'event StrategyRemovedFromQueue(address indexed strategy)',
  'event StrategyAddedToQueue(address indexed strategy)',
  'event UpdateHealthCheck(address indexed healthCheck)',
  'function initialize(address token, address governance, address rewards, string nameOverride, string symbolOverride) @666005',
  'function initialize(address token, address governance, address rewards, string nameOverride, string symbolOverride, address guardian) @666005',
  'function initialize(address token, address governance, address rewards, string nameOverride, string symbolOverride, address guardian, address management) @666005',
  'function initialize(address token, address governance, address rewards, string nameOverride, string symbolOverride, address guardian, address management, address healthCheck) @666005',
  'function apiVersion() pure returns (string) @6017',
  'function setName(string name) @111493',
  'function setSymbol(string symbol) @76349',
  'function setGovernance(address governance) @39565',
  'function acceptGovernance() @39436',
  'function setManagement(address management) @39625',
  'function setRewards(address rewards) @40206',
  'function setLockedProfitDegradation(uint256 degradation) @39638',
  'function setDepositLimit(uint256 limit) @39564',
  'function setPerformanceFee(uint256 fee) @39698',
  'function setManagementFee(uint256 fee) @39728',
  'function setGuardian(address guardian) @42350',
  'function setEmergencyShutdown(bool active) @42424',
  'function setWithdrawalQueue(address[10] queue) @658461',
  'function transfer(address receiver, uint256 amount) returns (bool) @80358',
  'function transferFrom(address sender, address receiver, uint256 amount) returns (bool) @124003',
  'function approve(address spender, uint256 amount) returns (bool) @39601',
  'function increaseAllowance(address spender, uint256 amount) returns (bool) @44222',
  'function decreaseAllowance(address spender, uint256 amount) returns (bool) @44248',
  'function permit(address owner, address spender, uint256 amount, uint256 expiry, bytes signature) returns (bool) @96051',
  'function totalAssets() view returns (uint256) @8633',
  'function returnShares(address user) view returns (uint256) @3386',
  'function deposit() returns (uint256) @188304',
  'function deposit(uint256 _amount) returns (uint256) @188304',
  'function deposit(uint256 _amount, address recipient) returns (uint256) @188304',
  'function maxAvailableShares() view returns (uint256) @273345',
  'function withdraw() returns (uint256) @2258580',
  'function withdraw(uint256 maxShares) returns (uint256) @2258580',
  'function withdraw(uint256 maxShares, address recipient) returns (uint256) @2258580',
  'function withdraw(uint256 maxShares, address recipient, uint256 maxLoss) returns (uint256) @2258580',
  'function pricePerShare() view returns (uint256) @27703',
  'function addStrategy(address strategy, uint256 debtRatio, uint256 minDebtPerHarvest, uint256 maxDebtPerHarvest, uint256 performanceFee) @942956',
  'function addStrategy(address strategy, uint256 debtRatio, uint256 minDebtPerHarvest, uint256 maxDebtPerHarvest, uint256 performanceFee, uint256 profitLimitRatio) @942956',
  'function addStrategy(address strategy, uint256 debtRatio, uint256 minDebtPerHarvest, uint256 maxDebtPerHarvest, uint256 performanceFee, uint256 profitLimitRatio, uint256 lossLimitRatio) @942956',
  'function updateStrategyDebtRatio(address strategy, uint256 debtRatio) @124991',
  'function updateStrategyMinDebtPerHarvest(address strategy, uint256 minDebtPerHarvest) @48377',
  'function updateStrategyMaxDebtPerHarvest(address strategy, uint256 maxDebtPerHarvest) @48407',
  'function updateStrategyPerformanceFee(address strategy, uint256 performanceFee) @43665',
  'function setHealthCheck(address _healthCheck) @43438',
  'function migrateStrategy(address oldVersion, address newVersion) @815546',
  'function revokeStrategy() @74133',
  'function revokeStrategy(address strategy) @74133',
  'function addStrategyToQueue(address strategy) @649008',
  'function removeStrategyFromQueue(address strategy) @6024449',
  'function debtOutstanding() view returns (uint256) @22169',
  'function debtOutstanding(address strategy) view returns (uint256) @22169',
  'function creditAvailable() view returns (uint256) @31714',
  'function creditAvailable(address strategy) view returns (uint256) @31714',
  'function availableDepositLimit() view returns (uint256) @21212',
  'function expectedReturn() view returns (uint256) @12876',
  'function expectedReturn(address strategy) view returns (uint256) @12876',
  'function report(uint256 gain, uint256 loss, uint256 _debtPayment) returns (uint256) @820591',
  'function sweep(address token) @24584',
  'function sweep(address token, uint256 amount) @24584',
  'function name() view returns (string) @14039',
  'function symbol() view returns (string) @11798',
  'function decimals() view returns (uint256) @3810',
  'function balanceOf(address arg0) view returns (uint256) @4106',
  'function allowance(address arg0, address arg1) view returns (uint256) @4402',
  'function totalSupply() view returns (uint256) @3900',
  'function token() view returns (address) @3930',
  'function governance() view returns (address) @3960',
  'function management() view returns (address) @3990',
  'function guardian() view returns (address) @4020',
  'function healthCheck() view returns (address) @4050',
  'function strategies(address arg0) view returns (tuple(uint256 performanceFee, uint256 activation, uint256 debtRatio, uint256 minDebtPerHarvest, uint256 maxDebtPerHarvest, uint256 lastReport, uint256 totalDebt, uint256 totalGain, uint256 totalLoss)) @21315',
  'function withdrawalQueue(uint256 arg0) view returns (address) @4155',
  'function emergencyShutdown() view returns (bool) @4140',
  'function depositLimit() view returns (uint256) @4170',
  'function debtRatio() view returns (uint256) @4200',
  'function totalDebt() view returns (uint256) @4230',
  'function lastReport() view returns (uint256) @4260',
  'function activation() view returns (uint256) @4290',
  'function lockedProfit() view returns (uint256) @4320',
  'function lockedProfitDegradation() view returns (uint256) @4350',
  'function rewards() view returns (address) @4380',
  'function managementFee() view returns (uint256) @4410',
  'function performanceFee() view returns (uint256) @4440',
  'function nonces(address arg0) view returns (uint256) @4736',
  'function DOMAIN_SEPARATOR() view returns (bytes32) @4500',
]
