export const PCNV_REDEMPTION_ABI = [
  'constructor(address _CNV)',
  'event Approval(address indexed owner, address indexed spender, uint256 amount)',
  'event Mint(uint256 indexed _amount)',
  'event OwnerUpdated(address indexed user, address indexed newOwner)',
  'event Paused(bool indexed _paused)',
  'event Redemption(address indexed _from, address indexed _who, uint256 indexed _amount)',
  'event Transfer(address indexed from, address indexed to, uint256 amount)',
  'function CNV() view returns (address)',
  'function DOMAIN_SEPARATOR() view returns (bytes32)',
  'function LINEAR_VESTING_TIME_LENGTH() view returns (uint256)',
  'function LINEAR_VESTING_TIME_START() view returns (uint256)',
  'function MAX_SUPPLY() view returns (uint256)',
  'function VESTING_AMOUNT_LENGTH() view returns (uint256)',
  'function VESTING_AMOUNT_START() view returns (uint256)',
  'function VESTING_TIME_END() view returns (uint256)',
  'function VESTING_TIME_START() view returns (uint256)',
  'function allowance(address, address) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function balanceOf(address) view returns (uint256)',
  'function decimals() view returns (uint8)',
  'function mint(address to, uint256 amount)',
  'function name() view returns (string)',
  'function nonces(address) view returns (uint256)',
  'function owner() view returns (address)',
  'function paused() view returns (bool)',
  'function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s)',
  'function redeem(uint256 _amount, address _who, address _to, bool _max) returns (uint256 amountOut)',
  'function redeemable(address _who) view returns (uint256)',
  'function redeemed(address) view returns (uint256)',
  'function setOwner(address newOwner)',
  'function setPause(bool _paused)',
  'function symbol() view returns (string)',
  'function totalMinted() view returns (uint256)',
  'function totalSupply() view returns (uint256)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) returns (bool)',
  'function vestedPercent(uint256 _time) pure returns (uint256)',
]
