import { ChainId } from '../enums'
import { ChainName } from '../enums'

export const CHAIN_NAME: { [chainId: number]: ChainName } = {
  [ChainId.ETHEREUM]: ChainName.ETHEREUM,
  [ChainId.ROPSTEN]: ChainName.ROPSTEN,
  [ChainId.RINKEBY]: ChainName.RINKEBY,
  [ChainId.GÖRLI]: ChainName.GÖRLI,
  [ChainId.KOVAN]: ChainName.KOVAN,
  [ChainId.MATIC]: ChainName.MATIC,
  [ChainId.MATIC_TESTNET]: ChainName.MATIC_TESTNET,
  [ChainId.FANTOM]: ChainName.FANTOM,
  [ChainId.FANTOM_TESTNET]: ChainName.FANTOM_TESTNET,
  [ChainId.XDAI]: ChainName.XDAI,
  [ChainId.BSC]: ChainName.BSC,
  [ChainId.BSC_TESTNET]: ChainName.BSC_TESTNET,
  [ChainId.ARBITRUM]: ChainName.ARBITRUM,
  [ChainId.ARBITRUM_TESTNET]: ChainName.ARBITRUM_TESTNET,
  [ChainId.MOONBEAM_TESTNET]: ChainName.MOONBEAM_TESTNET,
  [ChainId.AVALANCHE]: ChainName.AVALANCHE,
  [ChainId.AVALANCHE_TESTNET]: ChainName.AVALANCHE_TESTNET,
  [ChainId.HECO]: ChainName.HECO,
  [ChainId.HECO_TESTNET]: ChainName.HECO_TESTNET,
  [ChainId.HARMONY]: ChainName.HARMONY,
  [ChainId.HARMONY_TESTNET]: ChainName.HARMONY_TESTNET,
  [ChainId.OKEX]: ChainName.OKEX,
  [ChainId.OKEX_TESTNET]: ChainName.OKEX_TESTNET,
  [ChainId.CELO]: ChainName.CELO,
  [ChainId.PALM]: ChainName.PALM,
  [ChainId.PALM_TESTNET]: ChainName.PALM_TESTNET,
  [ChainId.MOONRIVER]: ChainName.MOONRIVER,
  [ChainId.FUSE]: ChainName.FUSE,
  [ChainId.TELOS]: ChainName.TELOS,
  [ChainId.MOONBEAM]: ChainName.MOONBEAM,
}
